# 一、defer
- 作用: 确保调用在函数结束是发生，一般用 defer 来释放资源
- 调用的时机
    1. Open/Close
    2. Lock/Unlock
    3. PrintHeader/PrintFooter
- defer 会有一个栈，先定义的 defer 先入栈，函数结束后，再将栈中的代码逐个出栈执行
- defer 不受 panic 和 return 影响，照样会执行
- 参数在 defer 语句时计算

```go
func tryDefer() {
    defer fmt.Println(1)
    defer fmt.Println(2)
    fmt.Println(3)
}
tryDefer()
// 3
// 2 (函数结束后执行)
// 1 (函数结束后执行)
```
> 用 defer 来释放资源

```go
func writeFile(filename string) {
    file, err := os.Create(filename)
    if err != nil {
        panic(err)
    }
    defer file.Close()
    
    writer := bufio.NewWriter(file)
    defer writer.Flush() // 函数结束后，从 buffer 写入文件
    
    f := Fibonacci() // 一个创建斐波那契数列的函数
    for i := 0; i < 20; i++ {
        fmt.Fprintln(writer, f())
    }
}

func main() {
    writeFile("fib.txt")
}
```
> 参数在 defer 语句时计算

```go
func tryDefer() {
    for i := 0; i < 100; i++ {
        defer fmt.Println(i)
        if i == 30 {
            panic("printed too many")
        }
    }
}
tryDefer()
// 会先从 30 开始打印到 0，然后再报错 "printed too many"
// 可见 defer 时并不是函数结束时再计算参数的。否则应该会打印 30 个 30
```

***

# 二、panic 和 recover
> go 语言一般少用 panic，而是用返回错误来进行错误处理

- panic:
    1. 停止当前函数执行
    2. 一直向上返回，执行每一层的 defer
    3. 如果没有在 defer 中遇见 recover，程序退出
- recover
    1. 仅在 defer 调用中使用
    2. 可获取 panic 的值
    3. 如果无法处理，可重新 panic

```go
package main

import (
    "errors"
    "fmt"
)

func tryRecover() {
    defer func() {
        r := recover()
        
        // 如果是错误则处理
        if err, ok := r.(error); ok {
            fmt.Println("Error occurred: ", err)
        } else {
            // 如果之前 panic 的参数不是 error，那么 repanic
            panic(fmt.Sprintf("I don't know what to do: %v", r))
        }
    }()
    
    // panic 一个错误
    panic(errors.New("this is an error"))
}

func main() {
    tryRecover() // 输出 "Error occurred: this is an error"
}
```

***

# 三、错误处理
- return error vs. panic
    1. 意料之中的错误使用 return error (如文件打不开)，意料外的使用 panic (如数组越界)

```go
func writeFile(filename string) {
    file, err := os.Create(filename, os.O_EXCL|os.O_CREATE, 0666)
    // 上面的代码是否出错，可以通过 err 是否有来判断
    if err != nil {
        // 1. panic("file already exists") // go 中一般不常用 panic 来处理错误
        
        // 2. err 是一个 error interface，其有一个 Error 方法可以返回错误信息
        // fmt.Println("Error:", err.Error())
        
        // 3. 我们还可更细化的来处理错误，Create 返回的 err 是一个 *ox.PathError 类型
        if pathError, ok := err.(*os.PathError); !ok {
            panic(err) // 未知错误，不知咋处理就只好直接 panic 了
        } else {
            // 针对 PathError 的处理
            fmt.Println(pathError.Op, pathError.Path, pathError.Err)
        }
        
        return // 由于报错了，中断流程
    }
    defer file.Close()
    
    writer := bufio.NewWriter(file)
    defer writer.Flush() // 函数结束后，从 buffer 写入文件
    
    f := Fibonacci() // 一个创建斐波那契数列的函数
    for i := 0; i < 20; i++ {
        fmt.Fprintln(writer, f())
    }
}
```
```go
// 自定义 error
func f() error {
    return  errors.New("this is a custom error")
}
err := f()
if err != nil {
    // ....
}

// 由于 error 是一个 interface，所以我们也可自己实现一个 error struct
```

## 1. 例子 (无错误处理)
```go
package main

import (
    "net/http"
    "io"
    "io/ioutil"
)

func main() {
    // 访问 http://localhost:8888/list/dir/a.txt 就可以访问到 dir/a.txt 文件内容了
    // 但是如该文件不存在，程序会直接报错(panic 了)，不过 panic 会保护 http server，所以程序不会崩溃
    http.HandleFunc("/list/", func FileListing(
        writer http.ResponseWriter, request *http.Request) {
        
        path := request.URL.Path[len("/list/"):]
        file, err := os.Open(path)
        if err != nil {
            // http.Error(Writer, err.Error(), http.StatusInternalServerError) // 页面输出错误
            panic(err)
        }
        defer file.Close()
        
        all, err := ioutil.ReadAll(file)
        if err != nil {
            panic(err)
        }
        
        writer.Write(all)
    })
    
    err := http.ListenAndServe(":8888", nil)
    if err != nil {
        panic(err)
    }
}
```

## 2. 例子 (实现统一的错误处理逻辑)
```go
// handler/filelisting.go
package handler

import (
    "net/http"
    "strings"
    "io/ioutil"
)

// 自定义错误，实现 userCanViewError interface
type userError string

func (e userError) Error() string {
    return e.Message()
}

func (e userError) Message() string {
    return string(e)
}

const prefix = "/list/"
// handler 函数
func FileListing(writer http.ResponseWriter, request *http.Request) error {
    if strings.Index(request.URL.Path, prefix) != 0 {
        return userError("path must start " + "with " + prefix)
    }
    path := request.URL.Path[len(prefix):]
    file, err := os.Open(path)
    if err != nil {
        return err // 有错误则 return 错误
    }
    defer file.Close()
    
    all, err := ioutil.ReadAll(file)
    if err != nil {
        return err
    }
    
    writer.Write(all)
    return nil // 无措的话，return nil
}
```
```go
package main

import (
    "net/http"
    "io"
    "io/ioutil"
    "handler"
    "log"
)


// 可暴露给用户的错误
type userCanViewError interface {
    error // 系统看的错误
    Message() string // 用户看的错误信息
}

type appHandler func(writer http.ResponseWriter, request *http.Request) error

// 包装 handler，用于统一处理错误，这样 handler 函数中如有错误，return 即可
// 错误会统一由该包装容器进行处理
func errWrapper(
    handler appHandler) func(writer http.ResponseWriter, request *http.Request) {
    
    return func(writer http.ResponseWriter, request *http.Request) {
        // recover 一些 panic 来的错误
        defer func() {
            if r := recover(); r != nil {
                log.Printf("Panic: %v", r)
                
                // 如果是可给用户看的错误，则在页面输出错误信息
                if userErr, ok := err.(userCanViewError); ok {
                    // .Message() 是给用户看的，.Error() 是给系统看的
                    http.Error(writer, userErr.Message(), http.StatusBadRequest)
                    
                    return
                }
                // 非可给用户看的错误，则页面输出标准错误信息
                code := http.StatusInternalServerError
                http.Error(writer, http.StatusText(code), code)
            }
        }()
        
        // 接收 handler 返回的错误
        err := handler(writer, request)
        if err != nil {
            // 处理错误
            log.Printf("Error handling request: %s", err.Error())
            
            code := http.StatusOK
            switch {
            // 文件不存在的错误
            case os.IsNotExist(err):
                code = http.StatusNotFound
            // 权限错误
            case os.IsPermission(err):
                code = http.StatusForbidden
            // 其他错误
            default:
                code = http.StatusInternalServerError
            }
            // 二参是字符串，也可写 err.Error()，但是这样就把内部错误暴露外部了，所以调试时才用
            http.Error(writer, http.StatusText(code), code)
        }
    }
}

func main() {
    // 访问 http://localhost:8888/list/dir/a.txt 就可以访问到 dir/a.txt 文件内容了
    // 文件不存在的话，页面会显示 404 错误，错误在 errWrapper 中被处理了
    http.HandleFunc("/list/", errWrapper(handler.FileListing))
    
    err := http.ListenAndServe(":8888", nil)
    if err != nil {
        panic(err)
    }
}
```

***
